### ISSUE TITLE
Dependency on networkmanager-openvpn?

### ISSUE THREAD

**Issue by arsh5620** [Zylquinal/protonvpn-bin#1]
Hi, 

First of all thank you for this helpful package, I made a build and installed the app but I kept on getting error while trying to connect:

```
2023-07-01T18:07:23.528490 | proton.vpn.app.gtk.widgets.main.exception_handler:133 | CRITICAL | APP:CRASH | Unexpected error.
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/site-packages/proton/vpn/backend/linux/networkmanager/core/tcpcheck.py", line 85, in _check_connectivity
    callback(is_any_port_reachable(ip_address, ports, timeout))
  File "/usr/lib/python3.11/site-packages/proton/vpn/backend/linux/networkmanager/core/networkmanager.py", line 76, in start_if_server_reachable
    future = self._setup()  # Creates the network manager connection.
             ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/proton/vpn/backend/linux/networkmanager/protocol/openvpn/openvpn.py", line 136, in _setup
    self._configure_connection(vpnconfig)
  File "/usr/lib/python3.11/site-packages/proton/vpn/backend/linux/networkmanager/protocol/openvpn/openvpn.py", line 54, in _configure_connection
    self.connection = self._import_vpn_config(vpnconfig)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/proton/vpn/backend/linux/networkmanager/core/networkmanager.py", line 338, in _import_vpn_config
    raise NotImplementedError(
NotImplementedError: Support for given configuration is not implemented
```

Turns out I hadn't installed the `networkmanager-openvpn` dependency, now I am not sure how to write PKGBUILDs so I am not sure if its possible, but if it is can we add that as a dependency to the build?

uname: `Linux asus-laptop 6.1.31-2-MANJARO #1 SMP PREEMPT_DYNAMIC Sun Jun  4 12:31:46 UTC 2023 x86_64 GNU/Linux`

**Comment by Zylquinal** [comment]
Fixed, just realized about that!
