### ISSUE TITLE
protonvpn-app fails to start with python error. Missing dependency maybe?

### ISSUE THREAD

**Issue by queenbiscuit311** [Zylquinal/protonvpn-bin#3]
The PKGBUILD builds and installs fine, but the program fails to actually work. Here's the terminal output:

```/home/sarah/.local/lib/python3.11/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (5.2.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/bin/protonvpn-app", line 33, in <module>
    sys.exit(load_entry_point('proton-vpn-gtk-app==4.0.0', 'console_scripts', 'protonvpn-app')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/protonvpn-app", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/proton/__init__.py", line 1, in <module>
    from .api import Session # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/proton/api.py", line 29, in <module>
    from .metadata import MetadataBackend
  File "/usr/lib/python3.11/site-packages/proton/metadata/__init__.py", line 1, in <module>
    from . import textfile_metadata # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/proton/metadata/textfile_metadata.py", line 6, in <module>
    from ._base import MetadataBackend
  File "/usr/lib/python3.11/site-packages/proton/metadata/_base.py", line 2, in <module>
    from ..utils import SubclassesMixin
ImportError: cannot import name 'SubclassesMixin' from 'proton.utils' (/usr/lib/python3.11/site-packages/proton/utils/__init__.py)
```

**Comment by queenbiscuit311** [comment]
I made sure to install everything from the PKGBUILD, but if that's not the issue then something must be wrong with upsteam I would guess.

**Comment by Zylquinal** [comment]
Can you try https://github.com/Zylquinal/protonvpn-bin/tree/dep-fix

**Comment by Zylquinal** [comment]
![image](https://github.com/Zylquinal/protonvpn-bin/assets/80770188/161ff606-5796-4178-9d35-a02a91ccd9ce)

It works for me, what about you?

**Comment by EchterAlsFake** [comment]
For me the problem was always that I had some old protonvpn packages installed. Make sure to uninstall them all, delete the python lib files and then reboot your computer before installing protonvpn-bin.

1) sudo pacman -R protonvpn protonvpn-cli protonvpn-gui protonvpn-bin
2) sudo rm -rf /usr/lib/python3.11/site-packages/proton
3) reboot
4) git clone https://github.com/Zylquinal/protonvpn-bin
5) makepkg -si

I can't test it right now, but that's what worked for me in the past.

**Comment by Zylquinal** [comment]
> For me the problem was always that I had some old protonvpn packages installed. Make sure to uninstall them all, delete the python lib files and then reboot your computer before installing protonvpn-bin.
> 
>     1. sudo pacman -R protonvpn protonvpn-cli protonvpn-gui protonvpn-bin
> 
>     2. sudo rm -rf /usr/lib/python3.11/site-packages/proton
> 
>     3. reboot
> 
>     4. git clone https://github.com/Zylquinal/protonvpn-bin
> 
>     5. makepkg -si
> 
> 
> I can't test it right now, but that's what worked for me in the past.

![image](https://github.com/Zylquinal/protonvpn-bin/assets/80770188/7e52fb01-772d-4a09-8a9e-ea4c6ae4e6bf)

Tested, and it's indeed caused by old protonvpn version, never use one so i never realize about it.

**Comment by queenbiscuit311** [comment]
Can confirm, those instructions fixed it. Thanks!
